### ISSUE TITLE
Graph module dependency on the config module for vue.js?

### ISSUE THREAD

**Issue by pb66** [emoncms/graph#102]
Shouldn't vue.js be moved to the main emoncms repo if multiple modules depend on it?

https://github.com/emoncms/graph/blob/866bd600ed08f0759f947befd9cd321344c2ca2a/view.php#L50

This is the error message displayed when navigating to the graph page (or refreshing it) if the config module is not installed.

![image](https://user-images.githubusercontent.com/5606042/63634856-29105700-c654-11e9-92c1-ae982a99efa9.png)

**Comment by borpin** [comment]
Someone else caught out by this https://community.openenergymonitor.org/t/vue-not-defined/11804

**Comment by emrysr** [comment]
the vuejs file was available in the Lib directory. I hadn't linked to the correct file. fixed in pull #103

**Comment by borpin** [comment]
I've just pulled this and I'm still getting the same error. Checked cache and restarted webserver.

**Comment by emrysr** [comment]
hi @borpin, 
I'd changed the source of the javascript to an existing file in the emoncms repo (3 months old):
https://github.com/emrysr/emoncms/blob/master/Lib/vue.min.js

If you use this domain http://localhost/emoncms you should be able to see it with this link...
http://localhost/emoncms/Lib/vue.min.js

Can you see the file?


[screenshot of paths used in the html source]
![delwedd](https://user-images.githubusercontent.com/1466013/64002310-a418b800-cb01-11e9-9eb9-d6859f6ea690.png)

**Comment by borpin** [comment]
Ah, sorry, the PR has not been merged has it?

**Comment by emrysr** [comment]
no yet. 
you could test it with this:
```
git checkout -b emrysr-fix/issue-102-vue-device-dependency master
git pull https://github.com/emrysr/graph.git fix/issue-102-vue-device-dependency
```

**Comment by borpin** [comment]
Yep that fixes it :)
